"""Write image-generation briefs in the same style/body/prompt format as Sift v3."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "docs/presentation/v1"
REFERENCE = ROOT.parent / "Agentic-production/sift/docs/presentation/v3/style.txt"
style = REFERENCE.read_text(encoding="utf-8").replace('27-slide deck about "Sift"', '12-slide deck about "Local System One"')
style = style.replace('"SIFT"', '"LAYA / RICHDALE"').replace('Sift-owned', 'application-owned')
style = style.replace('the bulk of findings that do not matter', 'the full finding inventory; no finding is suppressed')
slides = [
    ("LOCAL SYSTEM ONE", "Cover. Left-aligned title and subtitle, restrained stacked bars on the right, no placeholders.",
     'EYEBROW: RICHDALE AI\nSUBTITLE: Fast decision hints for Sift, Bugsmith and VPN QA\nSUPPORTING LINE: Measured on your RTX 4050 with real repository issues and QA evidence.\nMETADATA: 01 OCT 2026 · LOCAL BENCHMARK'),
    ("THE REAL WORKLOAD", "Inventory. Two repository cards above four horizontal category bars. Emphasize the dependency bar in amber. No pie chart.",
     'LEFT CARD: GhostShield · 134 open issues\nRIGHT CARD: TotalGuard · 99 open issues\nBARS: 196 dependency findings; 22 credential-related findings; 5 source-code findings; 10 business reports\nFOOTNOTE: Semantic work categories: two SAST credential findings join the 20 secret findings. Snapshot: 01 Oct 2026.\nCALLOUT: Seven QA observations from three reports; repeated failures are not independent bugs.'),
    ("DECIDE FIRST. INVESTIGATE NEXT.", "Three large cards connected left to right. First amber decision card, second navy evidence card, third navy repair card. Separate rose forbidden rail below.",
     'CARD 1: SYSTEM ONE\nSubtext: Small fixed choices · probabilities · milliseconds\nCARD 2: REASONING AGENT\nSubtext: Inspect evidence · reproduce · verify cause\nCARD 3: CONTROLLED REPAIR\nSubtext: Policy gates · regression tests · human review\nFORBIDDEN RAIL: A classification never authorizes a tool call, suppresses a finding or proves a vulnerability.'),
    ("ONE LOCAL GPU WORKER", "Architecture. Three small client boxes on left connect to bearer-auth API in center. Queue then single CUDA worker then one resident checkpoint on right. Three checkpoint names below worker. Offline cache at bottom.",
     'CLIENTS: React portal; HTTP apps; MCP agents\nAPI: FastAPI · port 8000 · bearer key\nQUEUE: Eight outstanding jobs · serialized inference\nWORKER: Python + PyTorch · RTX 4050 · CUDA only\nCHECKPOINTS: English; Multilingual; Typed decisions\nCACHE: Offline weights · pinned revision\nRULE: Unload before switching. GPU failure returns an error; no CPU retry.'),
    ("A FAIR LOCAL COMPARISON", "Methodology. Four equal tiles with large numbers, then a simple comparison rail from frozen corpus to three models to recorded outputs.",
     'TILE 1: 247 · distinct decision cases\nTILE 2: 3 · repeated passes per checkpoint\nTILE 3: 2,223 · single-request predictions\nTILE 4: 288 · additional batched states\nSETTINGS: Same inputs and label order · 512 context tokens · 192 question tokens · batch size 32 · microbatch 2\nRESULT: CUDA verified · no truncation · repeated choices unchanged\nFOOTNOTE: Three warmup calls per model excluded from steady-state latency. Reference labels are evidence audits, not verified vulnerability truth.'),
    ("FAST ENOUGH FOR A HINT", "Measured table with three rows and four columns. Stacked bars under table compare median latency; amber highlight fastest multilingual bar. Numbers exact, no invented values.",
     'TABLE HEADERS: Checkpoint | Median | p95 | Batch states/s\nROW 1: English | 61.53 ms | 76.52 ms | 28.26\nROW 2: Multilingual | 51.43 ms | 67.56 ms | 35.54\nROW 3: Typed decisions | 63.27 ms | 79.02 ms | 28.41\nFOOTNOTE: Resident-checkpoint service time on this corpus. First calls with switching: 2.41 s / 1.59 s / 2.06 s. Not an upstream speed guarantee.\nMEMORY NOTE: Observed allocated VRAM: 1.58 / 1.23 / 1.58 GiB. Post-call readings are not per-checkpoint peak measurements.'),
    ("ACCURACY DEPENDS ON THE TASK", "Measured table, three rows. Amber accent around typed security-topic cell. Below table, two separate footnote cards in slate and violet; do not use green pass styling.",
     'TABLE HEADERS: Checkpoint | Issue workflow / 233 | Security topic / 7 | QA cause / 7\nROW 1: English | 225 | 4 | 4\nROW 2: Multilingual | 170 | 3 | 0\nROW 3: Typed decisions | 222 | 7 | 4\nBASELINE NOTE: Always choosing dependency update matches 196 / 233 issues (84.1%). Use scanner metadata first.\nLIMITATION NOTE: Only seven topic and seven QA cases. All QA decisions stayed below the 0.8 review threshold. Confidence is not correctness.'),
    ("THE CARD-REQUIRED TRIAL", "Evidence comparison. Left card CURRENT CONTRACT, center card OLD TEST, right card ALL THREE MODELS. Below, a solid deterministic fix lane highlighted amber and dashed model advice lane violet.",
     'CURRENT CONTRACT: GhostShield trial activation now requires a credit card.\nOLD TEST: GS-018 expected an automatic trial after email verification. Actual page: paywall.\nALL THREE MODELS: Predicted PRODUCT_BUG. Missed the evidence reference: TEST_BUG.\nAPPLIED FIX: Update the GhostShield profile to expect no automatic trial. Keep token-revocation assertions intact.\nBOUNDARY: No trial purchase or credit-card charge was executed. A model cannot approve a policy change.'),
    ("SIFT: TOPIC HINTS IN SHADOW", "Architecture. Main solid line scanners to severity/intelligence to independent evidence verifier to issue lifecycle. Dashed branch from redacted candidate metadata to local Laya, returns only a small specialist hint card. Rose forbidden rail.",
     'MAIN LINE: Scanner findings → monotonic priority → independent verifier → GitHub lifecycle\nSHADOW BRANCH: Redacted metadata → typed-decisions → specialist hint event\nHINT EXAMPLES: Authentication/session · secret handling · code correctness\nAPPLIED: Optional REVIEWER_LAYA_URL and REVIEWER_LAYA_API_KEY. Disabled by default; timeout falls back.\nNEVER: Downgrade severity, auto-suppress findings, replace evidence validation or log source excerpts.'),
    ("BUGSMITH: THE RIGHT WORK LANE", "Four investigation lanes as stacked horizontal cards. Dependency grouping card amber. Current QA repair pipeline in solid navy below; dependency and credential lanes remain separate dashed extensions.",
     'DEPENDENCIES: 196 findings → 34 repository/package work groups\nCREDENTIALS: Owner review → confirm exposure → rotation plan\nSOURCE CODE: Reproduce → local regression → bounded repair\nBUSINESS REPORTS: Route to the operator; no code repair task\nAPPLIED: Read-only backlog planner and optional QA disagreement hints.\nBOUNDARY: Current Bugsmith policy forbids dependency upgrades. No automatic upgrade, secret rotation or issue closure.'),
    ("VPN QA: CONTRACT BEFORE CLASSIFIER", "Two tracks. Solid main line Playwright assertions to captured evidence to existing reasoning triage to report. Dashed Laya shadow branch from redacted evidence returns probability labels. Two evidence case cards below.",
     'MAIN LINE: Playwright → evidence → reasoning triage → report\nSHADOW: Trusted contract + redacted facts → Laya → optional report metadata\nCASE 1: GhostShield GS-018 · outdated automatic-trial expectation\nCASE 2: TotalGuard GS-027 / GS-028 · signed-out app tokens still validate\nAPPLIED: Optional QA_LAYA_URL and QA_LAYA_API_KEY. Test results and notification policy stay authoritative.\nBOUNDARY: Preserve sign-out security assertions. Never turn a failure green using a classification.'),
    ("START WITH MEASURED ADVICE", "Rollout. Three numbered cards connected left to right, then a four-line delivery list. Single amber emphasis on independent evaluation, no unmeasured savings claim.",
     'STEP 1: Enable optional shadow adapters locally\nSTEP 2: Compare advice against independent evidence\nSTEP 3: Expand the evaluation before any automated gate\nDELIVERED: Real-data corpus and GPU measurements\nDELIVERED: Portal examples and advisory HTTP workflows\nDELIVERED: Three optional repository adapters and QA contract correction\nDELIVERED: Four diagrams, reproducible prompts and this deck\nFINAL LINE: Fast decisions help organize investigation. Evidence and policy control action.'),
]
for name in ("bodies", "prompts", "out"):
    (DEST / name).mkdir(parents=True, exist_ok=True)
(DEST / "style.txt").write_text(style, encoding="utf-8")
for i, (title, layout, content) in enumerate(slides, 1):
    body = f'SLIDE NUMBER (bottom right): "{i:02d} / 12"\nARCHETYPE: {layout}\n\nTITLE, exact text: {title}\n\n{content}\n'
    (DEST / f"bodies/{i:02d}.txt").write_text(body, encoding="utf-8")
    (DEST / f"prompts/slide-{i:02d}.txt").write_text(style + body, encoding="utf-8")
print(f"Prepared {len(slides)} slide briefs in {DEST}")
